project:
  type: website

website:
  title: "ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: Page de présentation
      - href: projets.qmd
        text: Projets

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



